version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - 3333:3333
    environment:
      PORT: 3333
      DATABASE_URL: posgres://testing-app:testing-app@database/nest-testing
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: testing-app
      POSTGRES_PASSWORD: testing-app
      POSTGRES_DB: nest-testing
